# Generated by Django 5.0 on 2024-05-03 10:54

import signPdf.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signPdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="client",
            managers=[
                ("objects", signPdf.managers.UsuarioManager()),
            ],
        ),
    ]
