# Generated by Django 4.1.5 on 2023-12-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signPdf', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_signature',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_title',
            field=models.CharField(max_length=200),
        ),
    ]
