# Generated by Django 5.0 on 2023-12-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signPdf', '0003_alter_document_document_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(default=12345, max_length=500),
            preserve_default=False,
        ),
    ]
