# Generated by Django 5.0 on 2023-12-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signPdf", "0004_document_document_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_hash",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
