name: Django CI

on:
  push:
    branches: [ dev ]
    paths:
    - 'backend/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'backend/**'

jobs:
  build-backend:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.7]

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Make migrations
      run: | 
        cd backend
        python manage.py makemigrations

    - name: Run migrations
      run: | 
        cd backend
        python manage.py migrate

    - run: echo "🍏 This job's status is ${{ job.status }}."
        
